package com.MoveInSync.vendorManagement.enumClass;

public enum ActivityAction {
    DOCUMENT_DELETED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,
    DOCUMENT_UPLOADED,
    DRIVER_STATUS_CHANGED,
    DRIVER_DELETED,
    VEHICLE_STATUS_CHANGED,
    VEHICLE_DELETED,
    VENDOR_BLOCKED,
    VENDOR_UNBLOCKED,
    VENDOR_DELETED
}
